[connections.telecom]
    type="sql"
    dialect="postgresql"
    username="postgres"
    password="1q2w3e4r"
    host="10.10.1.161" # IP or URL
    port= 5432 # Port number
    database="telecom" # Database name

    